import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { QRCodeSVG } from 'qrcode.react';
import { createTransfer, socketURL } from './services/api';
import { parseChunk, sendFile, TransferClient } from './services/transferClient';
import { createHash, digestHex, hashFile } from './services/integrity';
import { createReceiverSink, type ReceiverSink } from './services/receiverStorage';
import type { Metadata } from './types';

const chunkSize = 2 * 1024 * 1024;
const bytes = (value: number) => value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : value < 1024 ** 3 ? `${(value / 1024 ** 2).toFixed(2)} MB` : `${(value / 1024 ** 3).toFixed(2)} GB`;
function Shell({ children }: { children: ReactNode }) { return <main><header><Link to="/" className="brand"><span>◈</span> relay</Link><span className="privacy">Temporary by design</span></header>{children}<footer>Files stream through memory only. Nothing is permanently stored.</footer></main>; }

function Home() {
  const navigate = useNavigate(); const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const choose = (selected?: File) => { if (selected) setFile(selected); };
  async function create() { if (!file) return; setBusy(true); setError(''); try { const sha256 = await hashFile(file, chunkSize); const result = await createTransfer({ fileName:file.name, fileSize:file.size, mimeType:file.type || 'application/octet-stream', chunkSize, sha256 }); navigate(`/transfer/${result.id}`, { state: { file, url:result.url, sha256 } }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create transfer.'); setBusy(false); } }
  return <Shell><section className="hero"><p className="eyebrow">PRIVATE FILE RELAY</p><h1>Send files without leaving a trail.</h1><p className="lede">A fast, temporary bridge between your devices. Your file is streamed while you need it, then forgotten.</p><div className="card dropzone" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); choose(event.dataTransfer.files[0]); }}>{file ? <><div className="file-icon">↗</div><h2>{file.name}</h2><p>{bytes(file.size)} <span className="muted">· {file.type || 'Unknown type'}</span></p><div className="actions"><button className="secondary" onClick={() => input.current?.click()}>Change file</button><button onClick={create} disabled={busy}>{busy ? 'Hashing file…' : 'Create transfer link →'}</button></div></> : <><div className="upload-mark">↑</div><h2>Drop a file here</h2><p>or choose one from this device</p><button onClick={() => input.current?.click()}>Choose a file</button></>}<input ref={input} hidden type="file" onChange={event => choose(event.target.files?.[0])} /></div>{error && <p className="error">{error}</p>}<div className="trust"><span>⌁</span><div><strong>No permanent storage</strong><br/><span>Links expire automatically after 15 minutes.</span></div><span>◷</span><div><strong>Streamed in chunks</strong><br/><span>Integrity checked with SHA-256.</span></div></div></section></Shell>;
}

function Sender() {
  const { transferId } = useParams(); const location = useLocation(); const details = location.state as { file: File; url: string; sha256: string } | undefined; const [progress, setProgress] = useState(0); const [waiting, setWaiting] = useState(true); const [error, setError] = useState(''); const client = useRef<TransferClient | undefined>(undefined); const abort = useRef(new AbortController());
  useEffect(() => { if (!transferId || !details?.file) return; const transfer = new TransferClient(socketURL(transferId), 'sender', transferId); client.current = transfer; const remove = transfer.onMessage(message => { if (message.type === 'transfer_accepted') { setWaiting(false); void sendFile(transfer, details.file, { fileName:details.file.name, fileSize:details.file.size, mimeType:details.file.type || 'application/octet-stream', chunkSize, sha256:details.sha256 }, value => setProgress(value / details.file.size), abort.current.signal).catch(reason => setError(reason instanceof Error ? reason.message : 'Transfer failed.')); } if (message.type === 'sender_disconnected' || message.type === 'receiver_disconnected') setError('The other device disconnected.'); }); return () => { abort.current.abort(); remove(); transfer.close(); }; }, [transferId, details]);
  if (!details?.file) return <Shell><Empty title="Transfer details unavailable" text="Return home and create a new transfer link." /></Shell>;
  return <Shell><section className="hero compact"><p className="eyebrow">TRANSFER READY</p><h1>Share the bridge.</h1><div className="card status-card"><div className="qr"><QRCodeSVG value={details.url} size={148} /></div><div><p className="label">YOUR LINK</p><div className="linkbox">{details.url}<button onClick={() => navigator.clipboard.writeText(details.url)}>Copy</button></div><p className="waiting">{error ? `! ${error}` : waiting ? '◉ Waiting for receiver to accept…' : progress < 1 ? '◉ Sending and verifying…' : '✓ Transfer complete'}</p></div></div>{!waiting && <Progress value={progress} file={details.file} />}</section></Shell>;
}

function Receiver() {
  const { transferId } = useParams(); const [metadata, setMetadata] = useState<Metadata>(); const metadataRef = useRef<Metadata>(); const [state, setState] = useState('Connecting…'); const [progress, setProgress] = useState(0); const client = useRef<TransferClient | undefined>(undefined); const sink = useRef<ReceiverSink>(); const received = useRef<BlobPart[]>([]); const expectedChunk = useRef(0); const receivedBytes = useRef(0); const hash = useRef(createHash()); const writes = useRef(Promise.resolve());
  useEffect(() => { if (!transferId) return; const transfer = new TransferClient(socketURL(transferId), 'receiver', transferId); client.current = transfer; const removeJSON = transfer.onMessage(message => { if (message.type === 'transfer_offer' && message.metadata) { metadataRef.current = message.metadata; setMetadata(message.metadata); setState('Waiting for your approval'); } if (message.type === 'transfer_complete') void finishReceive(); if (message.type === 'error') setState(message.message || 'Transfer failed'); }); const removeBinary = transfer.onBinary(data => { try { const chunk = parseChunk(data); if (chunk.index < expectedChunk.current) return; if (chunk.index !== expectedChunk.current) { setState('Transfer failed: chunks arrived out of order.'); transfer.close(); return; } const current = metadataRef.current; if (!current || receivedBytes.current + chunk.bytes.byteLength > current.fileSize) { setState('Transfer failed: received too many bytes.'); transfer.close(); return; } const typed = new Uint8Array(chunk.bytes); hash.current.update(typed); receivedBytes.current += typed.byteLength; expectedChunk.current++; writes.current = writes.current.then(() => sink.current?.write(typed)); if (sink.current?.blobParts) received.current = sink.current.blobParts; setProgress(receivedBytes.current / current.fileSize); } catch { setState('Transfer failed: invalid chunk received.'); transfer.close(); } }); return () => { removeJSON(); removeBinary(); transfer.close(); }; }, [transferId]);
  async function finishReceive() { const current = metadataRef.current; if (!current) return; await writes.current; if (receivedBytes.current !== current.fileSize) { setState('Transfer failed: received size did not match.'); return; } const actualHash = digestHex(hash.current); if (current.sha256 && actualHash !== current.sha256) { setState('Transfer failed: SHA-256 verification failed.'); return; } await sink.current?.close(); if (sink.current?.blobParts) { const blob = new Blob(received.current, { type:current.mimeType }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = current.fileName; anchor.click(); } setProgress(1); setState('Download complete'); }
  async function accept() { const current = metadataRef.current; if (!current || !client.current) return; try { sink.current = await createReceiverSink(current.fileName, current.mimeType, current.fileSize); client.current.send({ type:'accept_transfer' }); setState('Receiving…'); } catch (reason) { setState(reason instanceof Error ? reason.message : 'Could not prepare the download.'); } }
  return <Shell><section className="hero compact"><p className="eyebrow">INCOMING TRANSFER</p><h1>{state === 'Download complete' ? 'File received.' : 'A file is waiting.'}</h1>{metadata ? <div className="card receive-card"><div className="file-icon">↘</div><h2>{metadata.fileName}</h2><p>{bytes(metadata.fileSize)} <span className="muted">· From another device</span></p>{state === 'Waiting for your approval' ? <div className="actions"><button onClick={() => void accept()}>Download file</button><button className="secondary" onClick={() => client.current?.send({ type:'reject_transfer' })}>Reject</button></div> : <><Progress value={progress} file={metadata} /><p className="muted">{state}</p></>}</div> : <div className="card message">{state}</div>}</section></Shell>;
}

function Progress({ value, file }: { value:number; file:{ name:string; fileSize?:number; size?:number } }) { const total = file.fileSize ?? file.size ?? 0; return <div className="progress-wrap"><div className="progress-label"><strong>{Math.round(value * 100)}%</strong><span>{bytes(Math.min(value * total, total))} / {bytes(total)}</span></div><div className="bar"><span style={{ width:`${value * 100}%` }} /></div><p className="muted">{value >= 1 ? `✓ ${file.name} verified by SHA-256` : file.name}</p></div>; }
function Empty({ title, text }: { title:string; text:string }) { return <section className="hero compact"><div className="card message"><h2>{title}</h2><p>{text}</p><Link to="/" className="button">Start over</Link></div></section>; }
export default function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/transfer/:transferId" element={<Sender />} /><Route path="/receive/:transferId" element={<Receiver />} /><Route path="*" element={<Empty title="Page not found" text="This transfer path does not exist." />} /></Routes>; }
